### PR TITLE
#836

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
Increased the bundler values for css and js from 2 to 15. Also added a .install file with update hooks to update legacy versions.

### CODE REVIEW

**Comment by mmilutinovic1313** [comment]
hmmm -- looking into this

**Comment by mmilutinovic1313** [comment]
Ah -- I've been spending too much time in Swift. I need ';' in PHP :P

**Comment by btopro** [comment]
put both of these in `elmsln_advagg_update_7000`

**Comment by btopro** [comment]
it probably would work anyway but can u make the vsets be number instead of string values. `15` instead of `'15'`

**Comment by btopro** [comment]
some internal testing w/ 15 bundles is that it's definitely faster! Is completely against traditional wisdom in this area but whatever :)

**Pull request merged**
