### PR TITLE
I589 ugly

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
Fixes #

### CODE REVIEW

**Comment by mmilutinovic1313** [comment]
This is perhaps the ugliest PR

**Comment by btopro** [comment]
yeah this doesnt look right tho i dono why, ill have to piece through it :p

**Comment by mmilutinovic1313** [comment]
Take your time - I'll look through the files some more tomorrow too...there was just a lot of weird stuff...but it was a fresh install so it's probably related to the module.

**Comment by btopro** [comment]
looks like a view got removed or something



~!Bryan

________________________________

**Comment by btopro** [comment]
@mmilutinovic1313 steps to take to work towards wth is going on here.

- do a PR for JUST flag module being included in the courses stack (you had it in the right place I believe)
- then do a PR for JUST the upgrade part

This way we can make sense of 1 vs the other, also get the latest 0.7.x before pushing any of this in

**Comment by mmilutinovic1313** [comment]
Noted: I'll work on doing two seperate PRs then.

**Comment by mmilutinovic1313** [comment]
As far as what you mentioned with a view possibly being removed, should I use a clean install of the vagrant environment again to see if it's really a views issue?

**Comment by mmilutinovic1313** [comment]
In other news the PR for adding flag has been added in the same place

**Pull request closed without merging**
