### PR TITLE
Add node_revision_delete settings into mooc_cis_ux #1817

### PR DESCRIPTION
**Pull request by proconnor15**
#1817 added the dependency and the update function in mooc.install for the node revision delete module.

### CODE REVIEW

**Comment by mmilutinovic1313** [comment]
Looks like a good start! Make sure you add the settings in your features export of the module. This will allow them to be set by default when the update script runs. 

Also @btopro there seem to be extra settings that were overridden? Do these look okay? Or do you know where they came from and how to remove them?

**Comment by btopro** [comment]
stop using defaultconfig

**Comment by btopro** [comment]
the menu links probably shouldnt have been dropped either

**Comment by mmilutinovic1313** [comment]
@btopro that sounds good and the default-config is my fault. I didn't see the regular config menu in features export; only default-config and strongarm. Would we use strongarm instead of default-config then? Or just not add anything.

**Comment by btopro** [comment]
strongarm

**Pull request closed without merging**
