### PR TITLE
Jsmol

### PR DESCRIPTION
**Pull request by heyMP**
Added a new feature with the ICOR profile called ICOR Jmol.  This will add a content type to called Jmol which will allow you to upload Jmol specific files and render them through the HTML5 JSmol viewer.

### CODE REVIEW

**Comment by btopro** [comment]
looks great except I think we need https://www.drupal.org/project/jmol too or people need this dependency to use something flipping awesome like this

**Comment by btopro** [comment]
Also do a quick code review on the 2.x dev since I assume that's what your using. Hasn't seen love in awhile, might want to reach out to co-maintain.

**Comment by heyMP** [comment]
I have it in the local_modules folder within the interact stack.
https://github.com/elmsln/elmsln/tree/jsmol/core/dslmcode/stacks/interact/sites/all/modules/local_contrib/jmol

I'm using the 2.x dev branch as well.  There are a lot of features that we will probably want to add to it so I'll reach out to the maintainer.

**Comment by btopro** [comment]
weird... not seeing it in the PR but obviously there in that branch

**Pull request merged**
