### PR TITLE
Adding DDEV Support

### PR DESCRIPTION
**Pull request by JackWillDavis**
This PR adds support for running ELMSLN in DDEV.

The new script, `/scripts/install/handsfree/ddev/handsfree-ddev.sh`, is a little (very) hacky but thought it was a good way to make the core changes I needed to the installation scripts to make them ddev-friendly without editing core files. It uses PHP7.2 and the Ubuntu 18 installer.

It's working for me now, I have a base 1.0.6 version of ELMSLN running in DDEV.

Would be great if some others could test as well and get any feedback.

### CODE REVIEW

**Comment by btopro** [comment]
Accepting the merge and am testing now. As we didn't have a `.ddev` edition running this is not hurting anything active by accepting. Also the U18 installer was always on the fritz and I am aware of clean up there from other commits.

I'll let you know when it claims to have installed as it's running the scripts now..

**Comment by btopro** [comment]
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
W: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
debconf: delaying package configuration, since apt-utils is not installed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.xamaOf2fYP/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr 
task failed: Exec command 'sudo bash /var/www/html/scripts/install/handsfree/ddev/handsfree-ddev.sh elmsln ln elmsln.ddev.site http admin@elmsln.dev yes' in container/service 'web': Failed to run docker-compose [-f /home/bto108a/elmsln/.ddev/docker-compose.yaml exec -w /var/www/html/ -T web bash -c sudo bash /var/www/html/scripts/install/handsfree/ddev/handsfree-ddev.sh elmsln ln elmsln.ddev.site http admin@elmsln.dev yes], err='exit status 137', stdout='Setting up install files
Ign:1 http://deb.debian.org/debian stretch InRelease

**Comment by JackWillDavis** [comment]
Hmm might have to have a look at that over the weekend. 

Are you using ddev on Mac by any chance? I was using it with WSL2 in Win 10 and didn't see any of that...

That apt-key error seems to be something common. I know the ddev web container is Debian 10 so is the docker image for the web container or router expired? I'll refresh my ddev setup this weekend and try to run it again from scratch to see if I've not committed something just to make sure.

**Comment by btopro** [comment]
Ubuntu based device

**Comment by rickhumphries** [comment]
I was interested in testing this too. I installed ddev/docker from scratch and managed to get the installer to run through OK. ELMSLN is up and running. Needed to untick 'compress cached pages' after logging in and seems like there's an issue creating any courses, but the authorities are working.

image

**Comment by btopro** [comment]
If it works for you both that's awesome; merged in and happy about it, VERY happy about the contribution! However I can't make it work locally for whatever reason which is a bummer; might be a timeout issue w/ a certain package or networkign thing (my system has a lot of networkign issues). @heyMP could you pull master and try spinning this up when you get a chance.

**Pull request merged**
