### PR TITLE
Added local Angular Libraries Support #405 & #978

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
Added local support for Angular libraries. We will be using version 1.5.7 for now to start. This is now a library that is detectable by the Libraries API module and will eventually be able to be used with our CDN module (#991). We will need to run the `drush elms-sync-libs` command in order to hook the library into all the systems. This has the full angular library - so if we ever want to cut down on size, we can figure out which files we need / want to load.

### CODE REVIEW

**Comment by btopro** [comment]
uhhh yeah are you just trying to improve your line additions? this is 100k lines, what all is it @heyMP and why is it this big? Don't we just need the compressed versions and not the entire repo?

**Comment by mmilutinovic1313** [comment]
@btopro -- yeah the 100k lines is because angular (the library itself in its entirety) is a very big library. We could trim it down if you would like to just small essential files. Also with the easyCDN module I'm working on this should help prevent oversized libraries from always needing to be localized in their entireties.

**Comment by heyMP** [comment]
Yeah let's at least get rid of the angular/docs.  That takes up most of the file additions.

**Comment by mmilutinovic1313** [comment]
Removed that folder so that will reduce some of the lines of code / amount of space it takes up

**Comment by btopro** [comment]
still claims to be 102k additions. redo the commit again so that addition of a billion files isnt forever in peoples histories lol

**Comment by mmilutinovic1313** [comment]
Okay sounds good - I'm gonna close this PR and just redo them

**Pull request closed without merging**
