### PR TITLE
Removed dompdf dependencies on mooc_ux_defaults

### PR DESCRIPTION
**Pull request by JackWillDavis**
## Fixes ##

We get a 500 error when attempting to use a different print_pdf module library (i.e. wkhtmltopdf) when generating PDFs. Issue can be fixed by removing the dompdf_library helper module and removing the dependencies from mooc_ux_defaults.

## Commit Message ##

Removed dependencies on mooc_ux_defaults which was causing a 500 error when attempting to use a different library (i.e. wkhtmltopdf) for generating PDFs.

### CODE REVIEW

**Comment by btopro** [comment]
hmm.. we'll need something else in this that uses an install hook and maybe has a global setting you guys can implement to make it not enable. I get why you need to disable it but for people that DO use it it's autoconfigured out of the box to provide at least SOME solution until we rearchitect the whole thing to be pandoc delivered (at some point)

**Comment by btopro** [comment]
once #2168 is implemented via #2384 then we can accept this while at the same time removing all the stuff that provided it :)

**Comment by btopro** [comment]
@JackWillDavis changed my mind as we just had the DOMPDF stuff start bloating server calls bc of how much processing a single one was taking. only real way around this is to implement #2168 on a lambda or something

**Comment by JackWillDavis** [comment]
Yeah, went with WKHTMLTOPDF this end as it’s a little less bloaty. Lambda function might be better option long run though

**Comment by btopro** [comment]
yeah, the fact that it's affecting page performance to generate a PDF of something is kinda silly

**Pull request merged**
