### PR TITLE
Added a table template #785

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
(exported from the WYSIWYG editor) and two of the sass files for making tables responsive to the foundation_access theme in contrib. I checked to make sure adding these files didn't crash the system, and they don't. If someone can double check that these are in the right place that would be great! This is the first time I've added styling things to the system so I want to make sure I didn't break something :P. Let me know if there is anything i need to change.

https://github.com/elmsln/elmsln/issues/785

### CODE REVIEW

**Comment by mmilutinovic1313** [comment]
@heyMP + @btopro

**Comment by btopro** [comment]
ya will need testing after recompiling the sass file, which I can't do ;)

**Comment by btopro** [comment]
what's mooc--table.tpl.php about?

**Comment by mmilutinovic1313** [comment]
That has the table's html code with the imports to make it responsive. Basically I stuck the html from codepen into a template and exported it. I wasn't sure if that was the correct place for that file. But I figured it needed to be put somewhere after export so it could be picked up by the system.

**Pull request merged**
