### PR TITLE
#1256 CIS / Online Views Updated to Content-Caching

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
Content Caching now standard on CIS distro

### CODE REVIEW

**Comment by mmilutinovic1313** [comment]
Screenshotted problems with duplicate commits popping up on PRs -- will submit to github later today or this week.

**Comment by btopro** [comment]
Did you change the caching to any node type change or just the types that have influence of that view?

**Comment by mmilutinovic1313** [comment]
I did any node type change. I can do it with influence though if that is the preferred method?

**Comment by btopro** [comment]
they should only flush IF nodes that show up there are refreshed. For example, if a new unit is added, it shouldn't kill the offerings view. If a new course is added / updated, then ya

**Comment by mmilutinovic1313** [comment]
Hmm okay then -- that makes sense. I'll readjust those then to be set-up this way

**Comment by btopro** [comment]
closing without merge, we talked about this previously

**Comment by mmilutinovic1313** [comment]
Yup sounds good to me --

**Pull request closed without merging**
