### PR TITLE
#1848 Removed `fid` check for file_check as fid does not exis

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
This removes error caused in #1848. GitHub is adding your extra commits again...but only one file is changed so all should be good.

### CODE REVIEW

**Comment by btopro** [comment]
does this actually fix the issue (aka syllabus file does save correctly and is associated) or does this just make the error go away?

**Comment by mmilutinovic1313** [comment]
It tells me that I have to be outside of the master section to view it. I can see it in CIS. But I'm still not sure how to switch out of Master section in a course. Student view?

**Comment by mmilutinovic1313** [comment]
Creating a course with no section data to test...

**Comment by btopro** [comment]
unrelated issue, that would resolve itself after a nightly sync up (for the sections)
can't send section data at a course that doesn't yet exist. What we could do is after a system is built it could call home and say "what sections I got?". These "additional settings" aren't things we use currently so this is edge-casey to begin with as people add offerings to get more offerings into the system

**Comment by mmilutinovic1313** [comment]
That's fair - Well this does remove the message and the syllabus shows up on CIS for the course. So I'd say this fixes the issue because if the files don't exist it won't show up in the form state and therfore the if statement will resolve to false and not do a file_load.

**Comment by btopro** [comment]
that's all I needed to know ;)

**Comment by btopro** [comment]
@mmilutinovic1313 if u pull latest there's also a fix I pushed today that helps make sense when viewing master on a syllabus page as to how to resolve.

**Comment by mmilutinovic1313** [comment]
Sounds good - I'm putting 2 screenshots in here as reference :)

pdf saved

they saved

**Pull request merged**
