### PR TITLE
"My Profile" button for Anonymous users in flyout menu

### PR DESCRIPTION
**Pull request by JackWillDavis**
Currently the "My Profile" link tries to appear for Anonymous users in the flyout menu, despite no data being available.

The `cis-lmsless-template.tpl.php` template is currently checking that `<?php if (!empty($username)) : ?>` however `$username` automatically defaults to "Anonymous" [here](https://github.com/elmsln/elmsln/blob/0.11.x/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module#L331) which results in a blank button (as in the screenshot below).

my profile link

This PR just adds a second to check to make sure the button isn't rendered for Anonymous users.

### CODE REVIEW

**Comment by btopro** [comment]
may want to wrap that Anonymous in a t() function. I have a feeling this can be overwritten / language specific. other then that sounds reasonable

**Comment by JackWillDavis** [comment]
Ahh good point! I’ll update it tomorrow morning.

**Comment by JackWillDavis** [comment]
I've updated with the `t()` function now

**Comment by btopro** [comment]
looks good, thanks for the fix

**Pull request merged**
