### PR TITLE
Foundation Access Template Features File

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
I have added new Image, Video, and Quote properties to the Foundation Access Template Feature File referenced at https://github.com/elmsln/elmsln/issues/206. These changes are made in a new folder in features called foundation_access_template.

### CODE REVIEW

**Comment by btopro** [comment]
@heyMP this PR is for the style guide elements currently there. For the sake of showing @mmilutinovic1313 the workflow I told him to name it this but I don't know that its the final name.

I think we should do one of three things w/ the name and packaging of this. These names could be...

- in textbook as that's where other templates are delivered from
- in foundation_access_templates name space since they work best in there
- in some kind of elmsln_style_guide or something project space since they are directly tied to the style guide

so PR looks good if feature is placed in the right project name space which I'll let @heyMP dictate today when you guys meet. Personally I think either foundation access or style guide based is the way to go. FA based would suggest this ONLY works w/ FA, style guide based would imply we could theoretically support new theme engines in the future w/ the same kind of styling (though that's nearly impossible in practice)

**Comment by heyMP** [comment]
I like the namespace `foundation_access_template`.  @mmilutinovic1313 can you change the `package` category of this feature from `Features` to `Foundation Access`

**Comment by heyMP** [comment]
Let also change the all of the images from `../unsplash.jpg` to `https://unsplash.it/1200/800/` so that they render properly.  We can always change this later.

**Comment by mmilutinovic1313** [comment]
@heyMP is the image change done in the WYSIWYG template creation step, or do I have to go in and change the source once the feature is created?

**Comment by heyMP** [comment]
Nice.  Looks good to me!

**Comment by heyMP** [comment]
ugh...  It looks like the WYSIWYG is stripping some elements from the components.  For instance, the `<figure> <figcaption> <aside>` tags are not allowed.  Now that's an easy fix we can add them to the list of allowed tags in the text formats page.

What I don't understand is it's actually completely removing `<a>` tags that are nested within `<figure>` tags.  I'm saving the component and when I go back to edit it the structure is completely different.

**Comment by heyMP** [comment]
Ok I found it.  It looks like we have to include `&nbsp;` in the `<a>` tags that don't have any text in them.  These are used for opening and closing icons for the media component and the imagelightbox.

@mmilutinovic1313 can you include `&nbsp;` in between the `<a>` tags that don't contain text.

For example:

`<a class="mediavideo__open icon-elmsmedia-black" href="#" title="Click to view video."></a>`

- to -

`<a class="mediavideo__open icon-elmsmedia-black" href="#" title="Click to view video.">&nbsp;</a>`

**Comment by btopro** [comment]
@heyMP the default input filter configuration for textbook is currently to remove all unknown tags. So, adding these to textbook's input filter will let them pass through. We may also want to consider dropping the limitations on input as we get closer and closer to HAX. the point of the limits was to enforce accessibility / design (via wyswyg) bc it wouldn't let you do things that were potentially inaccessible.

If we move WYSIYWG into the "advanced" category and that it's no longer the primary method of page production then I think it makes sense to let people do whatever they want in that mode (as we're actively incentivizing NEVER using it while NEVER taking it away)

**Comment by btopro** [comment]
foundation_access_template is singular, just sayin.

also could you do ://unsplash.it/1200/800/ for the links? it's weird I know but I believe browsers will then use the current request protocol in front of it (http for local vagrant stuff and https for live environments)

**Comment by heyMP** [comment]
@btopro I've been hearing that you don't have to do that anymore for https stuff. https://twitter.com/paul_irish/status/588502455530311680

Yeah it might make sense to change it from `foundation_access_template` to `foundation_access_templates`.  It has a much more intuitive connotation.  @mmilutinovic1313 I know it's a pain but would you be able to re-export the feature with the new name?

**Comment by mmilutinovic1313** [comment]
Yep yep. Not a problem. I'm on the case right now!

**Comment by mmilutinovic1313** [comment]
Double Checking before pushing: 

I have added the *&nbsp;* tag to the *image_lightboxed* part of the .inc file. 

I have left the HTTPS on the changed tag after reading the tweet @heyMP posted. -- @btopro and @heyMP Let me know if this is okay, or if you want me to change it

I have renamed the folder in the feature to foundation_access_templates

Let me know if this is all in order, or if I need to change any other things in either the WYSIWYG templates or the exported Features. Additionally, how do I get the code formmating inline for GitHub? I can't seem to figure that out.

**Comment by btopro** [comment]
That sounds correct to me

it's three ` in a row on a line to start it, the code, then three ` in a row on their own line to close it
```
some
code
here
```

**Comment by heyMP** [comment]
@btopro is this pull request good to go?  I'm going to start defining all of the foundation_access view modes in this feature.

**Comment by btopro** [comment]
sorta. you can accept but make sure you delete the duplicate name space; see https://github.com/mmilutinovic1313/elmsln/tree/master/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/features

There's currently _template and _templates

Do that and I think we're g2g

**Comment by btopro** [comment]
just realized I can do this and was overthinking. will merge it in then delete the duplicate. @mmilutinovic1313 in the future make sure to delete the old and then issue another commit when there are name space changes like this

**Comment by btopro** [comment]
@heyMP @mmilutinovic1313 good to go. merged then removed the duplicate

**Pull request merged**
