### PR TITLE
#826 (mooc_ux_defaults changed for testing)

### PR DESCRIPTION
**Pull request by mmilutinovic1313**
Switched out jammer with simplify for mooc_ux_defaults. Switch didn't brick system and changed settings loaded after re-export. Using this as a start for testing.

### CODE REVIEW

**Comment by btopro** [comment]
This looks reasonable; can you switch it from a defaultconfig item to strong arm. Difference is that we can revert (globally) these settings if they are strongarm vs defaultconfig we can't

**Comment by mmilutinovic1313** [comment]
Sounds good. I did a re-export with it as strongarm. I also added menu-links and other permission dependencies. Let me know if it looks good or if I need to remove any of the files.

**Comment by btopro** [comment]
what's the `menu links` or `view hidden fields`?

**Comment by mmilutinovic1313** [comment]
hidefieldsfromuser1

`view hidden fields` is used for the "hide from user 1" option it looks like. 

`menu links` was one of the feature export options that appeared along with simplify. It looked a little bit odd (see picture) as it had a bunch of " ---  " with it. I put it in because I thought we needed to include all of the options for simplify.

**Comment by btopro** [comment]
Oh no drop that I know what that is. Has to do with the menu links that appear in the admin menu (I dono why it's even giving the option to export this). Thanks for clarifying the user 1 thing

**Comment by mmilutinovic1313** [comment]
Should I remove the file too that got generated initially? (menu_links.inc)

**Comment by btopro** [comment]
yes

**Comment by btopro** [comment]
mooc_ux_defaults.features.defaultconfig.inc
 can be dropped too

**Pull request merged**
